version: '3.3'

services:

  bitcoin-ticker-exporter:
    image: us.gcr.io/lincl-206618/bitcoin-ticker-exporter
    build:
      context: .
    volumes:
      - ./docker/config/exporter.yml:/exporter.yml
    command: --exchange kraken --exchange buda --config /exporter.yml
    ports:
      - 9180:9180

  currency-exporter:
    image: niedbalski/currency-exporter:latest
    command: --apikey ${APILAYER_KEY}
    environment:
      - APILAYER_KEY
    ports:
      - 9181:9181

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/data
      - ./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/config/bitcoin.rules.example:/etc/prometheus/bitcoin.rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  pubsub:
    image: niedbalski/alertmanager-to-zmq:latest
    ports:
      - 9098:9098 #HTTP
      - 5563:5563 #ZMQ

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./docker/config/alertmanager.yml:/etc/prometheus/alertmanager.yml
    command:
      - --config.file=/etc/prometheus/alertmanager.yml
    ports:
      - 9093:9093

volumes:
  prometheus-data:
