# prometheus global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

#  external_labels:
#    monitor: xxx
#    environment: xxx
#    service: Prometheus
#    region: xxx

scrape_configs:

  - job_name: exporter

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ["bitcoin-ticker-exporter:9180"]

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
#
#
#rule_files:
#  - "rules.conf"
