# prometheus global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

rule_files:
  - "/etc/prometheus/bitcoin.rules"

#  external_labels:
#    monitor: xxx
#    environment: xxx
#    service: Prometheus
#    region: xxx

scrape_configs:
  - job_name: bitcoin-ticker-exporter
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ["bitcoin-ticker-exporter:9180"]

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - "alertmanager:9093"